# src/test/modules/Makefile

subdir = src/test/modules
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = test_planner
SUBDIRS += connection 
SUBDIRS += test_extensions 

$(recurse)
