# gpcontrib/temp_tables_stat/Makefile

MODULE_big = temp_tables_stat
OBJS = $(MODULE_big).o $(WIN32RES)

EXTENSION = $(MODULE_big)
PGFILEDESC = "Collect and show statictics on temporary tables"

DATA = $(MODULE_big)--0.1.sql

ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
else
subdir = gpcontrib/temp_tables_stat
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif
