#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/bloom
#
#-------------------------------------------------------------------------


subdir = src/backend/access/bloom
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = blinsert.o blscan.o blutils.o blvacuum.o

include $(top_srcdir)/src/backend/common.mk
