void test_a_partitioned_heap_table_with_data_can_be_upgraded(void **state);
void test_a_partition_table_with_newly_added_list_partition_can_be_upgraded(void **state);
void test_a_partition_table_with_newly_added_range_partition_can_be_upgraded(void **state);
void test_a_partition_table_with_default_partition_after_split_can_be_upgraded(void **state);
